apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc-backend
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  selector:
    app: {{ .Release.Name }}-backend
  type: ClusterIP
