apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-conf
data:
  default.conf: |-

        server {

            listen 80;

            location /stub_status {
                allow 127.0.0.1;
                deny all;
                stub_status on;
            }

            location /healthz {
                add_header Content-Type text/plain;
                return 200 'OK';
            }

            location /static {
                alias /static;
            }

            location / {
                proxy_pass http://{{ .Release.Name }}-svc-backend;
            }
        }
