apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontsvcname }}
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: {{ .Release.Name }}-nginx
  type: ClusterIP
