apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-init
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded, hook-failed
spec:
  backoffLimit: 5
  template:
    spec:
      containers:
      - name: {{ .Release.Name }}-init
        image: {{ .Values.initimg }}
        env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                key:  dbusername
                name: {{ .Release.Name }}-auth-db
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                key:  dbpassword
                name: {{ .Release.Name }}-auth-db
          - name: DB_HOST
            value: {{ .Values.dbhost }}
          - name: DB_NAME
            value: {{ .Values.dbname }}
      restartPolicy: OnFailure
