apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth-repo
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  repotoken: {{ .Values.repotoken | b64enc }}
  repousername: {{ .Values.repousername | b64enc }}
