apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth-db
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  dbpassword: {{ .Values.dbpassword | b64enc }}
  dbusername: {{ .Values.dbusername | b64enc }}
