controller:
  runAsUser: 0
  fsGroup: 0 
persistence:
  enabled: true
  storageClass: "efs-sc"
  accessMode: "ReadWriteMany"
  size: "12Gi"
controller:
  installPlugins:
    - kubernetes:1.30.1
    - docker-workflow:1.26
    - workflow-aggregator:2.6
    - git:4.10.0
    - configuration-as-code:1.54
    - github:1.34.1
    - gitlab-plugin:1.5.22
    - sonar:2.14
    - amazon-ecr:1.7
    - chucknorris:1.4
    - blueocean:1.25.2
    - greenballs:1.15.1